name: Test build in monorepo
on: push

jobs:
  build:
    runs-on: 'macos-12'
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: mxschmitt/action-tmate@v3
      - name: Create monorepo
        run: |
          mkdir monorepo
          cd monorepo
          echo '{"name":"rnos-monorepo-tester","version":"1.0.0","license":"MIT","private":true,"workspaces":{"packages":["RootApp","packages/PackageApp", "AppA", "AppB"],"nohoist":["**/react","**/react-dom","**/react-native","**/react-native/**","**/react-native-codegen","**/react-native-dev-menu"]}}' > package.json
          yarn
          mkdir packages
      - name: Create RootApp
        working-directory: monorepo
        run: npx react-native@next init RootApp --skip-install
      - name: Create PackageApp
        working-directory: monorepo/packages
        run: npx react-native@next init PackageApp --skip-install
      
      - name: Install dependencies for RootApp
        working-directory: monorepo/RootApp
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Install dependencies for PackageApp
        working-directory: monorepo/packages/PackageApp
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      
      - name: Setup hoisted Reanimated
        if: ${{ inputs.is_hoisted }}
        working-directory: monorepo
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }} -W

      - name: Install Pods for RootApp
        if: ${{ inputs.platform == 'iOS' }}
        working-directory: monorepo/RootApp/ios
        run: pod install
      - name: Install Pods for PackageApp
        if: ${{ inputs.platform == 'iOS' }}
        working-directory: monorepo/packages/PackageApp/ios
        run: pod install

      - name: Build iOS app RootApp
        if: ${{ inputs.platform == 'iOS' }}
        working-directory: monorepo/RootApp
        run: yarn react-native run-ios
      - name: Build iOS app PackageApp
        if: ${{ inputs.platform == 'iOS' }}
        working-directory: monorepo/packages/PackageApp
        run: yarn react-native run-ios